In [1]:
import os, time, json
import tmdbsimple as tmdb 
import pandas as pd
from tqdm.notebook import tqdm_notebook
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

In [2]:
!pip install tmdbsimple

Requirement already satisfied: tmdbsimple in /Users/sofiawang/anaconda3/envs/dojo-env/lib/python3.10/site-packages (2.9.1)
Requirement already satisfied: requests in /Users/sofiawang/anaconda3/envs/dojo-env/lib/python3.10/site-packages (from tmdbsimple) (2.29.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/sofiawang/anaconda3/envs/dojo-env/lib/python3.10/site-packages (from requests->tmdbsimple) (1.26.15)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/sofiawang/anaconda3/envs/dojo-env/lib/python3.10/site-packages (from requests->tmdbsimple) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /Users/sofiawang/anaconda3/envs/dojo-env/lib/python3.10/site-packages (from requests->tmdbsimple) (2023.5.7)
Requirement already satisfied: idna<4,>=2.5 in /Users/sofiawang/anaconda3/envs/dojo-env/lib/python3.10/site-packages (from requests->tmdbsimple) (3.4)

In [3]:
import json
with open('/Users/sofiawang/.secret/tmdb_api.json', 'r') as f:
    login = json.load(f)
login.keys()

dict_keys(['api_key'])

In [4]:
import tmdbsimple as tmdb

tmdb.API_KEY = login['api_key']

search = tmdb.Discover()

first_page_movies = search.movie(page=1)['results']

for movie_info in first_page_movies:
    movie_details = tmdb.Movies(movie_info['id']).info()
    
    imdb_id = movie_details.get('imdb_id')
    budget = movie_details.get('budget')
    revenue = movie_details.get('revenue')
    
    certification = (
        movie_details.get('release_dates', {}).get('results', [{}])[0]
        .get('release_dates', [{}])[0]
        .get('certification')
    )
    
    print("Title:", movie_info['title'])
    print("IMDb ID:", imdb_id)
    print("Budget:", budget)
    print("Revenue:", revenue)
    print("Certification:", certification)
    print("\n")

Title: Wonka
IMDb ID: tt6166392
Budget: 125000000
Revenue: 534652708
Certification: None


Title: Aquaman and the Lost Kingdom
IMDb ID: tt9663764
Budget: 205000000
Revenue: 397860076
Certification: None


Title: The Marvels
IMDb ID: tt10676048
Budget: 274800000
Revenue: 205600000
Certification: None


Title: Migration
IMDb ID: tt6495056
Budget: 72000000
Revenue: 192040800
Certification: None


Title: Lift
IMDb ID: tt14371878
Budget: 0
Revenue: 0
Certification: None


Title: Attack
IMDb ID: tt7529298
Budget: 0
Revenue: 0
Certification: None


Title: Napoleon
IMDb ID: tt13287846
Budget: 165000000
Revenue: 213400000
Certification: None


Title: Society of the Snow
IMDb ID: tt16277242
Budget: 65500000
Revenue: 0
Certification: None


Title: Wish
IMDb ID: tt11304740
Budget: 175000000
Revenue: 233595858
Certification: None


Title: The OctoGames
IMDb ID: tt18559720
Budget: 0
Revenue: 0
Certification: None


Title: Role Play
IMDb ID: tt12964320
Budget: 0
Revenue: 0
Certification: None


Title: The Painter
IMDb ID: tt30253266
Budget: 0
Revenue: 0
Certification: None


Title: Oppenheimer
IMDb ID: tt15398776
Budget: 100000000
Revenue: 952000000
Certification: None


Title: The Boy and the Heron
IMDb ID: tt6587046
Budget: 50000000
Revenue: 159000000
Certification: None


Title: Poor Things
IMDb ID: tt14230458
Budget: 35000000
Revenue: 33800000
Certification: None


Title: Granit
IMDb ID: tt17352384
Budget: 0
Revenue: 0
Certification: None


Title: Deep Fear
IMDb ID: tt14865406
Budget: 0
Revenue: 0
Certification: None


Title: One More Shot
IMDb ID: tt27110516
Budget: 0
Revenue: 0
Certification: None


Title: Barbie
IMDb ID: tt1517268
Budget: 145000000
Revenue: 1445638421
Certification: None


Title: Anyone But You
IMDb ID: tt26047818
Budget: 25000000
Revenue: 100221578
Certification: None

In [8]:
search = tmdb.Discover()

first_page_movies = search.movie(page=1)['results']

titles = []
imdb_ids = []
budgets = []
revenues = []
certifications = []

for movie_info in first_page_movies:
    movie_details = tmdb.Movies(movie_info['id']).info()
    
    titles.append(movie_info['title'])
    imdb_ids.append(movie_details.get('imdb_id'))
    budgets.append(movie_details.get('budget'))
    revenues.append(movie_details.get('revenue'))
    
    certification = (
        movie_details.get('release_dates', {}).get('results', [{}])[0]
        .get('release_dates', [{}])[0]
        .get('certification')
    )
    certifications.append(certification)

tmdb_data= pd.DataFrame({
    'imdb_id': imdb_ids,
    'budget': budgets,
    'revenue': revenues,
    'certification': certifications
})

print(tmdb_data)

       imdb_id     budget     revenue certification
0    tt6166392  125000000   534652708          None
1    tt9663764  205000000   397860076          None
2   tt10676048  274800000   205600000          None
3    tt6495056   72000000   192040800          None
4   tt14371878          0           0          None
5    tt7529298          0           0          None
6   tt13287846  165000000   213400000          None
7   tt16277242   65500000           0          None
8   tt11304740  175000000   233595858          None
9   tt18559720          0           0          None
10  tt12964320          0           0          None
11  tt30253266          0           0          None
12  tt15398776  100000000   952000000          None
13   tt6587046   50000000   159000000          None
14  tt14230458   35000000    33800000          None
15  tt17352384          0           0          None
16  tt14865406          0           0          None
17  tt27110516          0           0          None
18   tt1517268  145000000  1445638421          None
19  tt26047818   25000000   100221578          None

In [10]:
tmdb= pd.read_csv('Data/tmdb.csv.gz')
tmdb.head()

,adult,backdrop_path,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,...,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,certification
0,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",220000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",https://www.marvel.com/movies/the-avengers,24428,tt0848228,en,The Avengers,...,1518815515,143,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Some assembly required.,The Avengers,False,7.712,29620,PG-13
1,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",220000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",https://www.marvel.com/movies/the-avengers,24428,tt0848228,en,The Avengers,...,1518815515,143,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Some assembly required.,The Avengers,False,7.712,29620,PG-13
2,False,/qom1SZSENdmHFNZBXbtJAU0WTlC.jpg,NaN,29000000,"[{'id': 10749, 'name': 'Romance'}, {'id': 18, ...",http://www.newline.com/properties/notebookthe....,11036,tt0332280,en,The Notebook,...,115600000,123,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Behind every great love is a great story.,The Notebook,False,7.886,10874,PG-13